config/routes.rb
Rails.application.routes.draw do
 
  #static pages controller
  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  root 'gossips#index'

  #gossip controller 
  resources :gossips

  #user controller
  resources :users
  
  #cities controller
  resources :cities

  #comments controller
  resources :gossips do
    resources :comments
  end
  
  #sessions controller
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip, optional: true
  belongs_to :commentable, polymorphic: true, optional: true
  belongs_to :user
  has_many :likes
  has_many :comments, as: :commentable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:new, :edit, :update, :create, :destroy]

  def show
  end

  def new
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(params[:id])
    @gossip = Gossip.find(params[:gossip_id])
  end

  def create
    @comment = Comment.new('content' => params[:content],user: current_user, gossip: Gossip.find(params[:gossip_id]))
    if @comment.save
        redirect_to :controller => 'gossips', :action => 'show', notice: 'Success', :id => params[:gossip_id]
    else
      redirect_to :action => 'new'
    end
  end

  def update
    @comment = Comment.find(params[:id])
    comment_param = params.require(:comment).permit(:content)
    if @comment.update(comment_param)
      redirect_to :controller => 'gossips', action: 'show', :id => params[:gossip_id]
    else
      redirect_to :action => 'edit'
    end
  end

  def destroy
    if Comment.destroy(params[:comment_id])
      redirect_to :controller => 'gossips', action: "show", :id => params[:id]
    else
      redirect_to action: "show", :id => params[:id]
    end
  end

  def authenticate_user
    unless current_user
      flash[:notice] = "Tu n'as pas accès à cette page"
      redirect_to new_session_path
    end
  end 
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<!-- DISPLAY DU FORMULAIRE -->
<% content_for :title, "Edit a Comment" %>
<!-- Affichage Stylisé du Gossip-->
<% if !@comment.nil? && @comment.errors.any? %>
	<div class="alert alert-danger">
	  <p>We were not able to add your comment for the following reasons :</p>
	  <ul>
	    <% @comment.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	  </ul>
	</div>
<% end %>
<div class ='align-middle'>
	<div class="card mt-5 ml-5 mr-5" style="height:350px">
		<h5 class="card-title ml-5 pt-5 mb-2">Modifie ton commentaire</h5>
	  <div class="card-body">
		<%= form_for [@gossip,@comment] do |f| %>

	<div class=" form-group">
	<label class="card-title">Content </label>
	<%=f.text_area :content, :value => @comment.content, class: 'form-control' %>
	</div>
	<div class="form-group">
	    <button type="submit">Modifier</button>
	    <%= link_to 'Supprimer', gossip_comment_path(comment_id: @comment.id,id: @gossip.id), class: 'btn btn-danger ml-5', method: :delete%>
	</div>
<% end %>

app/views/comments/new.html.erb
<!-- DISPLAY DU FORMULAIRE DE CREATION DE COMMENTAIRE -->
<% content_for :title, "Commenter" %>
<!-- Affichage Stylisé du Gossip-->
<% if !@comment.nil? && @comment.errors.any? %>
	<div class="alert alert-danger">
	  <p>We were not able to add your comment for the following reasons :</p>
	  <ul>
	    <% @comment.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	  </ul>
	</div>
<% end %>



<div class ='align-middle text-center'>
	<div class="card m-5 p-5" style="height:300px">
		<div class="card-body">		
			<%= form_tag gossip_comments_path do %>
			  <h5 class="cart-title"><%= label_tag 'Laisser un commentaire' %></h5>
			  <p class="cart-title"><%= text_area_tag 'content', @comment.content %></p>
			  <br /> <br />
			  <%= submit_tag "Ajouter", class: 'btn btn-danger' %>
			<% end %>
		</div>
	</div>
</div>