config/routes.rb
Rails.application.routes.draw do
 
  #static pages controller
  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  root 'gossips#index'

  #gossip controller 
  resources :gossips

  #user controller
  resources :users
  
  #cities controller
  resources :cities

  #comments controller
  resources :gossips do
    resources :comments
  end
  
  #sessions controller
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  #utilisation de bcrypt
  has_secure_password

  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "RecipientList"

  #validation des attributs
  validates :password, presence: true, length: { minimum: 6 }

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "Cet e-mail n'est pas correct." }, uniqueness: true
  validates :age, :numericality => { :greater_than_or_equal_to => 0 }

  #stocker en base le remember_digest
  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
    end
  
  def show
    @user = User.find(params[:id])# Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
    @city = City.find(@user.city_id)
    @nb_gossips = Gossip.where(user_id: @user.id).count
    @nb_comments = Comment.where(user_id: @user.id).count
    @gossips_arrray = Gossip.where(user_id: @user.id)
  end
  
  def new
  # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end
  
  def create
    @user = User.new(
      city_id: params[:ville],
      email: params[:email],
      password: params[:password],
      first_name: params[:first_name],
      last_name: params[:last_name],
      description: params[:description],
      age: params[:age])
    if @user.save
      redirect_to new_session_path
      flash.now[:success] = "Compte crée avec succès"
    else 
      render "new"
    end

  end
  
  def edit
  # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end
  
  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end
  
  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<% if !@user.nil? && @user.errors.any? %>
    <div class="alert alert-danger">
      <p>Ton compte ne peut pas être crée pour les raisons suivantes :</p>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>



<div class="container">

<div class="card bg-light">
<article class="card-body mx-auto" style="max-width: 400px;">
	<p class="text-center">Rejoins la communauté Gossip Project</p>
    </p>

        <!--LE FORMULAIRE-->
	<form action= "<%= users_path %>" method="POST">

      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
              <div class="form-label-group">

		<!-- FIRST NAME -->
	<div class="form-group input-group">
		<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-user"></i> </span>
		 </div>
        <input name="first_name" class="form-control" placeholder="Prénom *" type="text">
    </div>

		<!-- LAST NAME -->
	<div class="form-group input-group">
		<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-user"></i> </span>
		 </div>
        <input name="last_name" class="form-control" placeholder="Nom de famille *" type="text">
    </div>

		<!-- DESCRIPTION -->
    	<div class="form-group input-group">
		<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-user"></i> </span>
		 </div>
        <input name="description" class="form-control" placeholder="Décris toi en quelques mots" type="text">
    </div>

    		<!-- AGE -->
    	<div class="form-group input-group">
		<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-user"></i> </span>
		 </div>
        <input name="age" class="form-control" placeholder="Âge" type="text">
    </div>

        <!-- EMAIL -->
    <div class="form-group input-group">
    	<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
		 </div>
        <input name="email" class="form-control" placeholder="Email *" type="email">
    </div>
          

      <!-- CITY -->
    <div class="form-group input-group">
    	<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-building"></i> </span>
		</div>
			<%= select_tag 'ville', options_from_collection_for_select(City.all.order(:name), 'id','name'), class: "form-control" %>
            <%= link_to 'Ville', new_city_path, class: 'btn btn-secondary btn-sm ml-2'%>
  </div> 
  
        <!-- PASSWORD -->
    <div class="form-group input-group">
    	<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
		</div>
        <input class="form-control" placeholder="Créer ton mot de passe*" type="password" name="password">
    </div>

      <!-- CONFIRM PASSWORD -->
    <div class="form-group input-group">
    	<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
		</div>
        <input class="form-control" placeholder="Confirme ton mot de passe*" type="password" name="password">
    </div>                                      
    <div class="form-group">
        <input type="submit" value="Crée ton compte" class="btn btn-primary btn-block">
 

    </div>  
    <p class="text-center">Tu as déjà un compte ?
    <%= link_to "Connecte toi !", new_session_path, :class => "text-center" %>    
    </p>                                                                 
</form>
</article>
</div> <!-- card.// -->

</div> 
<!--container end.//-->

app/views/users/show.html.erb
<br/>

<center>
 <div class="card border-secondary mb-6" style="max-width: 50rem;">
  <div class="card-header">---- Coordonnées de <%= @user.first_name %> ----</div>
    <div class="card-block">
      <p class="card-text">Prénom : <%= @user.first_name %></p>
      <p class="card-text">Nom de Famille : <%= @user.last_name %></p>
      <p class="card-text">Email : <%= @user.email %></p>
      <p class="card-text">Age : <%= @user.age %></p>
      <p class="card-text">Ville : <%= link_to @user.city[:name], city_path(:id => @user.city_id) %></p>
    </div>
  </div>
</center>

</body>