config/routes.rb
Rails.application.routes.draw do
 
  #static pages controller
  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  root 'gossips#index'

  #gossip controller 
  resources :gossips

  #user controller
  resources :users
  
  #cities controller
  resources :cities

  #comments controller
  resources :gossips do
    resources :comments
  end
  
  #sessions controller
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments
  has_many :likes

    #validation des attributs
    validates :title, length: {in: 3..14}
    validates :content, presence: true
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  
  #permet de savoir si l'utilisateur est connecté et lui laisser l'accès si c'est le cas 
  before_action :authenticate_user, only: [:new, :edit, :update, :create, :destroy]
  
  #permet de savoir si l'utilisateur et le propriétaire de l'élèment qu'il souhaite modigier
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comments = Comment.where(gossip_id: params[:id]).all

  end

  def new
    @gossip = Gossip.new # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire (new.html.erb)
  end

  def create
    @gossip = Gossip.new(title: params[:gossip_title], content: params[:gossip_content], user: current_user)
    @gossip.user = User.find_by(id: session[:user_id])

    if @gossip.save 
      redirect_to root_path
      flash[:success] = "Ton Gossip a été sauvegardé avec succès !" 
     else
      render "new"
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])# Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
    @gossip = Gossip.find(params[:id])
    gossip_params = params.require(:gossip).permit(:title, :content)
    @gossip.update(gossip_params)
    redirect_to action: "show"
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to :action => "index"
  end

  def authenticate_user
    unless current_user
      flash[:notice] = "Tu n'as pas accès à cette page"
      redirect_to new_session_path
    end
  end 

  def correct_user
    if is_owner?(Gossip.find(params[:id]).user_id)
      flash[:notice] = "Ton commentaire a été correctement modifié"

    else flash[:danger] = "Tu n'as pas accès à cette page"
      redirect_to gossips_path
    end
  end

end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<center>

<%content_for :title, "Editer" %>

<h1>Edite ton gossip</h1>


<%= form_for @gossip do |f| %>

<div class="form-group"> 

<label>Titre du gossip </label>

<%=f.text_field :title, class: 'form-control' %>

<label>Contenu du gossip </label>

<%=f.text_area :content, class: 'form-control' %>

</div>

<div class="form-group">
	<button type="submit">Modifier l'article </button>
</div>
<% end %>

</center>

app/views/gossips/index.html.erb
<title>The gossip project</title>

<% if params[:notice] %>
 <div class="alert alert-success">
  <strong>Success!</strong> We added your Gossip to the database.
</div>
<% end %>


<center>
  <div class="jumbotron" style="background-image :url(https://images.unsplash.com/photo-1496309732348-3627f3f040ee?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80); background-size: 100%;">
    <h1 class="display-4" style="color: white">Bienvenue !</h1>
    <img src="http://tgp.ae/wp-content/uploads/2017/03/TGP_Light_Logo.png">
    <hr class="my-4">
    <p style="color: white">Nous sommes ici pour gossiper entre nous.</p>
    <%= link_to "Créer un Gossip", new_gossip_path, :class => "btn btn-sm btn-outline-info" %>
  </div>


<div class="card-columns">
<% Gossip.all.each do |gossip| %>
 <div class="card text-white bg-dark mb-3" style="max-width: 23rem;">
  <div class="card-header bg-secondary">Gossip <%=gossip.id%></div>
    <div class="card-block">
      <p class="card-text">Auteur : <%= gossip.user.first_name %></p>
      <p class="card-text">Titre : <%= gossip.title %></p>
      <p class="card-text">Lien vers ce Gossip : <%= link_to gossip.title, gossip_path(:id => gossip.id) %></p>
      <p class="card-title"><%= Comment.where(gossip_id: gossip.id).count%> commentaires</p>
    </div>
  </div>
<% end %>
</div>
</center>

app/views/gossips/new.html.erb
<% if @gossip.errors.any? %>
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class ='align-middle text-center'>
	<div class="card m-5 p-5" style="height:300px">
		<div class="card-body">

			<form action= "<%= gossips_path %>" method="POST">

				<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

				<h3> Créé ton nouveau gossip !</h3>
				
				<div class="row justify-content-center">
					<p style = "width: 200px"> titre : <input type="text" name="gossip_title"></p>
				</div>
				<div class="row justify-content-center">
				<p style = "width: 200px">Contenu : <input type="text" name="gossip_content"></p>
				</div>
			  <p><input type="submit" value="Valider"></p>
			</form>		
		</div>
	</div>
</div>

app/views/gossips/show.html.erb
<br/>

<center>
 <div class="card border-secondary mb-6" style="max-width: 50rem;">
  <div class="card-header">---- Gossip n°<%= @gossip.id %> ----</div>
    <div class="card-block">
      <p class="card-text">Titre : <%= @gossip.title %></p>
      <p class="card-text">Contenu : <%= @gossip.content %></p>
      <p class="card-text">Crée le : <%= @gossip.created_at %></p>
      <p class="card-text">Publié par : <%= link_to @gossip.user.first_name, user_path(:id => @gossip.user_id ) %></p>
      <%= link_to "Modifier", edit_gossip_path, :class => "btn btn-sm btn-outline-secondary" %>
      <%= link_to "Supprimer", gossip_path, :class => "btn btn-sm btn-outline-secondary btn-danger", :data => {:confirm => "Êtes-vous sur?(e)"}, :method => :DELETE %>
      </div>
  </div>
</center>


<!-- DISPLAY DES COMMENTAIRES -->
<h3 class='text-center mt-5 mb-3'>Commentaires</h3>
<h1 class='text-center mt-2 mb-2'><%= link_to "Ajouter un commentaire", new_gossip_comment_path(@gossip.id), class: 'btn btn-secondary' %></h1>
<div class='container-list'>
	<div class="row">
		<% @comments.each do |comment| %>
			<div class="col-4 col-sm-4 col-md-4 col-lg-4 mt-5 text-center" style="width: 18rem">
			  <div class="card-body">
			    <h5 class="card-title">Commentaire de <%= link_to comment.user.first_name , users_path(:id => comment.user.id)%><fieldset></fieldset></h5>
					<p class="card-title"><%= comment.content %></p>
					<p class="card-title"><%= comment.created_at %></p>
			    <%= link_to "Modifier", edit_gossip_comment_path(@gossip.id, comment.id), class: 'btn btn-secondary' %>
			  </div>
			</div>
		<%end%>
	</div>
</div>