config/routes.rb
Rails.application.routes.draw do
 
  #static pages controller
  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  root 'gossips#index'

  #gossip controller 
  resources :gossips

  #user controller
  resources :users
  
  #cities controller
  resources :cities

  #comments controller
  resources :gossips do
    resources :comments
  end
  
  #sessions controller
  resources :sessions, only: [:new, :create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">THE GOSSIP PROJECT</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to "Accueil", root_path, class: 'nav-item nav-link' %>
          <%= link_to "Contact", contact_path, class: 'nav-item nav-link' %>
          <%= link_to "Team", team_path, class: 'nav-item nav-link' %>
        </div>
      </div>

      <li class="nav-link">
        <% if logged_in? %>
          <%= link_to current_user.first_name,  {controller: "users", action: "show", id: current_user.id}, :class => "nav_item active" %>
        <% else %>
          <%= link_to "S'inscrire", new_user_path, :class => "nav_item active" %>
        <% end %>  
      </li>

      <li class="nav-link">
        <% if logged_in? %>
        <%= link_to "Se déconnecter", session_path(session.id), method: :delete, :class => "nav_item active"%>
        <% else %>
        <%= link_to "Se connecter", new_session_path, :class => "nav_item active" %>
        <% end %> 
      </li> 

    </nav>

    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <!-- AFFICHER MESSAGES FLASHS -->
    <div><%= flash[:notice] %></div>

  <body>
    <%= yield %>
  </body>
</html>